- name: Install required packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop: ["apr-util-devel", "gcc", "pcre-devel", "libxml2-devel", "mariadb"]

- name: Install apache
  ansible.builtin.unarchive:
    src: "https://www-eu.apache.org/dist//httpd/httpd-2.4.54.tar.gz"
    dest: /root
    remote_src: yes

- name: Compile Apache
  shell: cd /root/httpd-2.4.54 ;./configure --enable-so;make;make install

- name: Create hard link
  ansible.builtin.copy:
    src: httpd
    dest: /etc/init.d/httpd
    mode: '0755'
    remote_src: false

- name: Restart service
  ansible.builtin.systemd:
    state: daemon-reload
    name: httpd

- name: Install php
  ansible.builtin.unarchive:
    src: "https://www.php.net/distributions/php-7.3.7.tar.gz"
    dest: /root
    remote_src: yes

- name: Install dependencies
  shell: cd /root/php-7.3.7 && ./configure --with-apxs2=/usr/local/apache2/bin/apxs --enable-mbstring --enable-mysqlnd --with-mysqli && make clean && make && make install

- name: Replace DirectoryIndex in httpd.conf file
  ansible.builtin.replace:
    path: /usr/local/apache2/conf/httpd.conf
    regexp: 'index.html'
    replace: '      DirectoryIndex index.html index.php'

- name: Add AddType configuration
  ansible.builtin.blockinfile:
    path: /usr/local/apache2/conf/httpd.conf
    insertafter: "#AddType application/x-gzip"
    block: |
      AddType application/x-httpd-php .php
      AddType application/x-httpd-php-source .phps

- name: Download mediawiki software
  ansible.builtin.unarchive:
    src: "https://releases.wikimedia.org/mediawiki/1.38/mediawiki-1.38.4.tar.gz"
    dest: /root
    remote_src: yes
    owner: daemon
    group: daemon

- name: Remove wiki folder
  ansible.builtin.file:
    path: /usr/local/apache2/htdocs/wiki
    state: absent

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/apache2/htdocs/wiki
    state: absent