- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Copy a "sudoers" file on the remote machine for editing
  ansible.builtin.copy:
    src: /tmp/frontend-main/static
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy Nginx Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy roboshop.conf
  ansible.builtin.template:
    src: localhost.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Systemd start service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Systemd start service
  ansible.builtin.debug: "hello"